version: '3.4'

services:
  ocelotgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  productmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  ordermicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  ui.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

